### ISSUE TITLE
BM2 / Vgate Battery Asst / BM3 / Same programmer but no compatibility

### ISSUE THREAD

**Issue by zonalimitatore** [KrystianD/bm2-battery-monitor#8]
Hello! Congratulations for the excellent work. I wanted to ask you something. I bought this gizmo, thinking the mobile app was BM2. Instead, the qrcode, refers me to a site where to download the app (not present in the playstore). The app in question is called Battery Asst. I noticed that the same programmer made all these apps. Now, since the app really sucks, (no badge, no notification, no export way,ecc...) I was trying all the various apps, but unfortunately none "see" the device (I was interested in BM2). What's in the app that won't connect, with a different app? Do you need to work on the app or on the device? Is it doable, in your opinion? Thank you.

I've decompiled both, but my programmer knowledges aren't for android app :(

**Comment by KrystianD** [comment]
Hi @zonalimitatore, unfortunately, I am not able to help, I have only this one device (BM2, single piece) and have no way of checking other ones.

> Is it doable, in your opinion?

For sure it is doable, it is just about the effort required :)
